services:
  postgres:
    container_name: postgres-db-rea-sys
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: rea_solutions
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - rea-solutions-network
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-rea-sys
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - rea-solutions-network

networks:
  rea-solutions-network:
    driver: bridge

volumes:
  postgres:
    driver: local
